# Generated by Django 2.1.1 on 2020-02-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='isPlaying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channels',
            name='playing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_playing', to='driver.Songs'),
        ),
        migrations.AddField(
            model_name='channels',
            name='timeTag',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='songs',
            field=models.ManyToManyField(related_name='songs', to='driver.Songs'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.Playlists'),
        ),
    ]
